// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Veritas Platform Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/exams": {
            "get": {
                "description": "List exams with  sorting and filtering support for the caller enterprise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "List exams",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by title (case-insensitive substring match)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 10, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (allowed: created_at, updated_at, title, duration_minutes, passing_score_percent, status) (default: created_at)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction (asc or desc) (default: desc)",
                        "name": "sort_dir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedResponse-Exam"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create one exam under the caller enterprise.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Create exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Exam payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateExamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Exam"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}": {
            "get": {
                "description": "Get one exam for the caller enterprise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Get exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Exam"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete one exam by ID.",
                "tags": [
                    "exam"
                ],
                "summary": "Delete exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update exam fields by ID.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Update exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Exam payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateExamRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/clone": {
            "post": {
                "description": "Clone exam content into a new exam with provided title.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Clone exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Source Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Clone payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CloneExamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Exam"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/close": {
            "post": {
                "description": "Close an active exam.",
                "tags": [
                    "exam"
                ],
                "summary": "Close exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/publish": {
            "post": {
                "description": "Publish exam after validation checks.",
                "tags": [
                    "exam"
                ],
                "summary": "Publish exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/questions": {
            "get": {
                "description": "Get question mappings for one exam with ",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Get exam questions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 10, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (allowed: order_index, points_override) (default: order_index)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction (asc or desc) (default: desc)",
                        "name": "sort_dir",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include answers and metadata (default: false)",
                        "name": "with_correct_answer",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedResponse-ExamQuestion"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Attach multiple questions to an exam with optional order indices.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Add questions to exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Exam questions payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AddExamQuestionsBulkRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ExamQuestion"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/questions/{questionId}": {
            "delete": {
                "description": "Remove one question mapping from exam.",
                "tags": [
                    "exam"
                ],
                "summary": "Remove question from exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update order index for an exam question mapping.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Update exam question mapping",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update mapping payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateExamQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/schedule": {
            "post": {
                "description": "Set start and end times for an exam.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Schedule exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Schedule payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ScheduleExamRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns a simple JSON indicating the service is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "operationId": "healthCheck",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/questions": {
            "get": {
                "description": "List questions with  sorting and filtering support for the caller enterprise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "List questions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 10, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (allowed: created_at, updated_at, title, difficulty, type, points) (default: created_at)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction (asc or desc) (default: desc)",
                        "name": "sort_dir",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include answers and metadata (default: false)",
                        "name": "with_correct_answer",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedResponse-Question"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create one question under the caller enterprise.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Create question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Question payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Question"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/questions/{questionId}": {
            "get": {
                "description": "Get a question by ID for the caller enterprise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Get question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Include answers and metadata (default: false)",
                        "name": "with_correct_answer",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Question"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete one question from the caller enterprise.",
                "tags": [
                    "question"
                ],
                "summary": "Delete question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update question fields by ID.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Update question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Question payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/questions/{questionId}/media": {
            "post": {
                "description": "Upload media (image, video, PDF) for a question. Max size 5MB.",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Upload media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Media file",
                        "name": "media",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UploadMediaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AddExamQuestionRequest": {
            "type": "object",
            "required": [
                "questionId"
            ],
            "properties": {
                "orderIndex": {
                    "type": "integer"
                },
                "questionId": {
                    "type": "string"
                }
            }
        },
        "AddExamQuestionsBulkRequest": {
            "type": "object",
            "required": [
                "questions"
            ],
            "properties": {
                "questions": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/AddExamQuestionRequest"
                    }
                }
            }
        },
        "CloneExamRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        },
        "CreateExamRequest": {
            "type": "object",
            "required": [
                "durationMinutes",
                "passingScorePercent",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "durationMinutes": {
                    "type": "integer"
                },
                "maxParticipants": {
                    "type": "integer"
                },
                "negativeMarking": {
                    "type": "boolean"
                },
                "passingScorePercent": {
                    "type": "number"
                },
                "settings": {
                    "type": "object",
                    "additionalProperties": true
                },
                "templateSourceId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "CreateQuestionRequest": {
            "type": "object",
            "required": [
                "content",
                "difficulty",
                "points",
                "title",
                "topic",
                "type"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "difficulty": {
                    "$ref": "#/definitions/DifficultyLevel"
                },
                "evaluationCriteria": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "expectedAnswer": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "mediaUrl": {
                    "type": "string"
                },
                "negativePoints": {
                    "type": "number"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/QuestionOptionDTO"
                    }
                },
                "points": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/QuestionType"
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "QuestionOptionDTO": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "isCorrect": {
                    "type": "boolean"
                }
            }
        },
        "ScheduleExamRequest": {
            "type": "object",
            "required": [
                "endTime",
                "startTime"
            ],
            "properties": {
                "endTime": {
                    "type": "string",
                    "example": "2026-03-01T12:00:00Z"
                },
                "startTime": {
                    "type": "string",
                    "example": "2026-03-01T10:00:00Z"
                }
            }
        },
        "UpdateExamQuestionRequest": {
            "type": "object",
            "properties": {
                "orderIndex": {
                    "type": "integer"
                }
            }
        },
        "UpdateExamRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "durationMinutes": {
                    "type": "integer"
                },
                "maxParticipants": {
                    "type": "integer"
                },
                "negativeMarking": {
                    "type": "boolean"
                },
                "passingScorePercent": {
                    "type": "number"
                },
                "settings": {
                    "type": "object",
                    "additionalProperties": true
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "UpdateQuestionRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "difficulty": {
                    "$ref": "#/definitions/DifficultyLevel"
                },
                "evaluationCriteria": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "expectedAnswer": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "mediaUrl": {
                    "type": "string"
                },
                "negativePoints": {
                    "type": "number"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/QuestionOptionDTO"
                    }
                },
                "points": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/QuestionType"
                }
            }
        },
        "UploadMediaResponse": {
            "type": "object",
            "properties": {
                "mediaUrl": {
                    "type": "string"
                }
            }
        },
        "Metadata": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "has_next": {
                    "type": "boolean"
                },
                "has_previous": {
                    "type": "boolean"
                },
                "page_size": {
                    "type": "integer"
                },
                "total_elements": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "PaginatedResponse-Exam": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Exam"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/Metadata"
                }
            }
        },
        "PaginatedResponse-ExamQuestion": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ExamQuestion"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/Metadata"
                }
            }
        },
        "PaginatedResponse-Question": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Question"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/Metadata"
                }
            }
        },
        "DifficultyLevel": {
            "type": "string",
            "enum": [
                "Easy",
                "Medium",
                "Hard"
            ],
            "x-enum-varnames": [
                "DifficultyEasy",
                "DifficultyMedium",
                "DifficultyHard"
            ]
        },
        "Exam": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "durationMinutes": {
                    "type": "integer"
                },
                "enterpriseId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "maxParticipants": {
                    "type": "integer"
                },
                "negativeMarking": {
                    "type": "boolean"
                },
                "passingScorePercent": {
                    "type": "number"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ExamQuestion"
                    }
                },
                "scheduledEnd": {
                    "type": "string"
                },
                "scheduledStart": {
                    "type": "string"
                },
                "settings": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "$ref": "#/definitions/ExamStatus"
                },
                "templateSourceId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "ExamQuestion": {
            "type": "object",
            "properties": {
                "examId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "orderIndex": {
                    "type": "integer"
                },
                "question": {
                    "$ref": "#/definitions/Question"
                },
                "questionId": {
                    "type": "string"
                }
            }
        },
        "ExamStatus": {
            "type": "string",
            "enum": [
                "Draft",
                "Scheduled",
                "Active",
                "Closed",
                "Archived"
            ],
            "x-enum-varnames": [
                "ExamDraft",
                "ExamScheduled",
                "ExamActive",
                "ExamClosed",
                "ExamArchived"
            ]
        },
        "Question": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "difficulty": {
                    "$ref": "#/definitions/DifficultyLevel"
                },
                "enterpriseId": {
                    "type": "string"
                },
                "evaluationCriteria": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "expectedAnswer": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "mediaUrl": {
                    "type": "string"
                },
                "negativePoints": {
                    "type": "number"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/QuestionOption"
                    }
                },
                "points": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/QuestionType"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "QuestionOption": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isCorrect": {
                    "type": "boolean"
                },
                "questionId": {
                    "type": "string"
                }
            }
        },
        "QuestionType": {
            "type": "string",
            "enum": [
                "MCQ",
                "TrueFalse",
                "ShortAnswer",
                "Essay"
            ],
            "x-enum-varnames": [
                "QuestionTypeMCQ",
                "QuestionTypeTrueFalse",
                "QuestionTypeShortAnswer",
                "QuestionTypeEssay"
            ]
        }
    },
    "tags": [
        {
            "description": "Exam lifecycle and assembly endpoints.",
            "name": "exam"
        },
        {
            "description": "Question bank management endpoints.",
            "name": "question"
        },
        {
            "description": "Operational and health endpoints.",
            "name": "system"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Veritas Exam Service API",
	Description:      "Exam authoring, scheduling, publishing, and question bank management service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
