// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Veritas Platform Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/exams": {
            "get": {
                "description": "List all exams for the caller enterprise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "List exams",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Exam"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create one exam under the caller enterprise.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Create exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Exam payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Exam"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Exam"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}": {
            "get": {
                "description": "Get one exam for the caller enterprise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Get exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Exam"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete one exam by ID.",
                "tags": [
                    "exam"
                ],
                "summary": "Delete exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update exam fields by ID.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Update exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Exam payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Exam"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/clone": {
            "post": {
                "description": "Clone exam content into a new exam with provided title.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Clone exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Source Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Clone payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CloneExamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Exam"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/close": {
            "post": {
                "description": "Close an active exam.",
                "tags": [
                    "exam"
                ],
                "summary": "Close exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/publish": {
            "post": {
                "description": "Publish exam after validation checks.",
                "tags": [
                    "exam"
                ],
                "summary": "Publish exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/questions": {
            "get": {
                "description": "Get question mappings for one exam.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Get exam questions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ExamQuestion"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Attach question to exam with optional override points and order index.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Add question to exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Exam question payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AddExamQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/ExamQuestion"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/questions/{questionId}": {
            "delete": {
                "description": "Remove one question mapping from exam.",
                "tags": [
                    "exam"
                ],
                "summary": "Remove question from exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update points override or order index for an exam question mapping.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Update exam question mapping",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update mapping payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateExamQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/rules": {
            "post": {
                "description": "Add rule for selecting random questions by topic/difficulty.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Add randomization rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rule payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ExamRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/ExamRandomizationRule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/rules/{ruleId}": {
            "delete": {
                "description": "Delete one randomization rule from an exam.",
                "tags": [
                    "exam"
                ],
                "summary": "Delete randomization rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rule ID (UUID)",
                        "name": "ruleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update topic/difficulty/questionCount for a rule.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Update randomization rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rule ID (UUID)",
                        "name": "ruleId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rule payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ExamRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exams/{examId}/schedule": {
            "post": {
                "description": "Set start and end times for an exam.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "exam"
                ],
                "summary": "Schedule exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exam ID (UUID)",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Schedule payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ScheduleExamRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns a simple JSON indicating the service is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "operationId": "healthCheck",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/questions": {
            "get": {
                "description": "List all questions for the caller enterprise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "List questions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Question"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create one question under the caller enterprise.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Create question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Question payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Question"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Question"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/questions/{questionId}": {
            "get": {
                "description": "Get a question by ID for the caller enterprise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Get question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Question"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete one question from the caller enterprise.",
                "tags": [
                    "question"
                ],
                "summary": "Delete question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update question fields by ID.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Update question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Question payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Question"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "DifficultyLevel": {
            "type": "string",
            "enum": [
                "Easy",
                "Medium",
                "Hard"
            ],
            "x-enum-varnames": [
                "DifficultyEasy",
                "DifficultyMedium",
                "DifficultyHard"
            ]
        },
        "Exam": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "durationMinutes": {
                    "type": "integer"
                },
                "enterpriseId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "invitationMethod": {
                    "description": "Email, Link, Token",
                    "type": "string"
                },
                "maxParticipants": {
                    "type": "integer"
                },
                "negativeMarking": {
                    "type": "boolean"
                },
                "passingScorePercent": {
                    "type": "number"
                },
                "questions": {
                    "description": "Relational data",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ExamQuestion"
                    }
                },
                "randomizationRules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ExamRandomizationRule"
                    }
                },
                "scheduledEnd": {
                    "type": "string"
                },
                "scheduledStart": {
                    "type": "string"
                },
                "settings": {
                    "type": "object",
                    "additionalProperties": true
                },
                "status": {
                    "$ref": "#/definitions/ExamStatus"
                },
                "templateSourceId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "ExamQuestion": {
            "type": "object",
            "properties": {
                "examId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "orderIndex": {
                    "type": "integer"
                },
                "pointsOverride": {
                    "type": "integer"
                },
                "question": {
                    "description": "populated if joined",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Question"
                        }
                    ]
                },
                "questionId": {
                    "type": "string"
                }
            }
        },
        "ExamRandomizationRule": {
            "type": "object",
            "properties": {
                "difficulty": {
                    "$ref": "#/definitions/DifficultyLevel"
                },
                "examId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "questionCount": {
                    "type": "integer"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "ExamStatus": {
            "type": "string",
            "enum": [
                "Draft",
                "Scheduled",
                "Active",
                "Closed",
                "Archived"
            ],
            "x-enum-varnames": [
                "ExamDraft",
                "ExamScheduled",
                "ExamActive",
                "ExamClosed",
                "ExamArchived"
            ]
        },
        "Question": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "difficulty": {
                    "$ref": "#/definitions/DifficultyLevel"
                },
                "enterpriseId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "mediaUrl": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "negativePoints": {
                    "type": "number"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/QuestionOption"
                    }
                },
                "points": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/QuestionType"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "QuestionOption": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isCorrect": {
                    "type": "boolean"
                },
                "questionId": {
                    "type": "string"
                }
            }
        },
        "QuestionType": {
            "type": "string",
            "enum": [
                "MCQ",
                "TrueFalse",
                "ShortAnswer",
                "Essay"
            ],
            "x-enum-varnames": [
                "QuestionTypeMCQ",
                "QuestionTypeTrueFalse",
                "QuestionTypeShortAnswer",
                "QuestionTypeEssay"
            ]
        },
        "AddExamQuestionRequest": {
            "type": "object",
            "required": [
                "questionId"
            ],
            "properties": {
                "orderIndex": {
                    "type": "integer"
                },
                "pointsOverride": {
                    "type": "integer"
                },
                "questionId": {
                    "type": "string"
                }
            }
        },
        "CloneExamRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "ExamRuleRequest": {
            "type": "object",
            "required": [
                "questionCount"
            ],
            "properties": {
                "difficulty": {
                    "$ref": "#/definitions/DifficultyLevel"
                },
                "questionCount": {
                    "type": "integer"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "ScheduleExamRequest": {
            "type": "object",
            "required": [
                "endTime",
                "startTime"
            ],
            "properties": {
                "endTime": {
                    "type": "string",
                    "example": "2026-03-01T12:00:00Z"
                },
                "startTime": {
                    "type": "string",
                    "example": "2026-03-01T10:00:00Z"
                }
            }
        },
        "UpdateExamQuestionRequest": {
            "type": "object",
            "properties": {
                "orderIndex": {
                    "type": "integer"
                },
                "pointsOverride": {
                    "type": "integer"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Exam lifecycle and assembly endpoints.",
            "name": "exam"
        },
        {
            "description": "Question bank management endpoints.",
            "name": "question"
        },
        {
            "description": "Operational and health endpoints.",
            "name": "system"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Veritas Exam Service API",
	Description:      "Exam authoring, scheduling, publishing, and question bank management service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
