// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Veritas Platform Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Validates email/password credentials and returns a JWT access token plus a refresh token.\nOnly users with roles SystemAdmin, EnterpriseAdmin, EnterpriseAuto, or EnterpriseStaff may authenticate via this service.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate a user",
                "operationId": "authLogin",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JWT access and refresh tokens",
                        "schema": {
                            "$ref": "#/definitions/TokenResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing or malformed request body",
                        "schema": {
                            "$ref": "#/definitions/BadRequestErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid email or password",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    },
                    "403": {
                        "description": "Account locked, inactive, deleted, or role not permitted",
                        "schema": {
                            "$ref": "#/definitions/ForbiddenErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/InternalErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Immediately revokes the supplied refresh token so it cannot be used for future token refreshes.\nThis endpoint is idempotent: invalid, unknown, expired, or already-revoked tokens return 204 to prevent token enumeration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Revoke a refresh token",
                "operationId": "authLogout",
                "parameters": [
                    {
                        "description": "Refresh token to revoke",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/logoutRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Token revoked — no content",
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing or malformed request body",
                        "schema": {
                            "$ref": "#/definitions/BadRequestErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/InternalErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Exchanges a valid refresh token for a new JWT access token and a rotated refresh token. The old refresh token is invalidated.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh an access token",
                "operationId": "authRefresh",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/refreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "New JWT access and refresh tokens",
                        "schema": {
                            "$ref": "#/definitions/TokenResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing or malformed request body",
                        "schema": {
                            "$ref": "#/definitions/BadRequestErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    },
                    "401": {
                        "description": "Refresh token invalid, revoked, or expired",
                        "schema": {
                            "$ref": "#/definitions/UnauthorizedErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/InternalErrorResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns a simple JSON indicating the service is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "operationId": "healthCheck",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Request correlation ID"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "BadRequestErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "invalid_request"
                },
                "message": {
                    "type": "string",
                    "example": "invalid request body"
                },
                "requestId": {
                    "type": "string",
                    "example": "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                }
            }
        },
        "ForbiddenErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "access_denied"
                },
                "message": {
                    "type": "string",
                    "example": "access denied"
                },
                "requestId": {
                    "type": "string",
                    "example": "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                }
            }
        },
        "InternalErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "internal_error"
                },
                "message": {
                    "type": "string",
                    "example": "internal server error"
                },
                "requestId": {
                    "type": "string",
                    "example": "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                }
            }
        },
        "TokenResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "expiresIn": {
                    "type": "integer",
                    "example": 3600
                },
                "refreshToken": {
                    "type": "string",
                    "example": "b8a54f0f0cc6d2f68dd0b457ea4bb7f814ff69ec487f474f5c6f1781b6f0a0d3"
                }
            }
        },
        "UnauthorizedErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "invalid_credentials"
                },
                "message": {
                    "type": "string",
                    "example": "invalid email or password"
                },
                "requestId": {
                    "type": "string",
                    "example": "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                }
            }
        },
        "loginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "admin@veritas.io"
                },
                "password": {
                    "type": "string",
                    "minLength": 1,
                    "example": "s3cur3P@ssw0rd"
                }
            }
        },
        "logoutRequest": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 64,
                    "example": "b8a54f0f0cc6d2f68dd0b457ea4bb7f814ff69ec487f474f5c6f1781b6f0a0d3"
                }
            }
        },
        "refreshRequest": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 64,
                    "example": "b8a54f0f0cc6d2f68dd0b457ea4bb7f814ff69ec487f474f5c6f1781b6f0a0d3"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Authentication endpoints for login, token refresh, and logout.",
            "name": "auth"
        },
        {
            "description": "Operational and health endpoints.",
            "name": "system"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Veritas Auth Service API",
	Description:      "JWT-based authentication service for the Veritas platform.\nHandles login, token refresh, and token revocation for privileged roles.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
