// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Veritas Platform Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/forgot-password": {
            "post": {
                "description": "Request a password reset link via email. Always returns 200 OK.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Forgot password",
                "parameters": [
                    {
                        "description": "Email address",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ForgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "post": {
                "description": "Set a new password using the token received in the password reset email.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Reset password via token",
                "parameters": [
                    {
                        "description": "Token and new password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises": {
            "get": {
                "description": "List enterprises with optional status and search filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enterprise"
                ],
                "summary": "List enterprises",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by slug or display name",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (display_name, slug, status, created_at)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction (asc, desc)",
                        "name": "sort_dir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedResponse-Enterprise"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Register a new enterprise with an owner account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enterprise"
                ],
                "summary": "Register enterprise",
                "parameters": [
                    {
                        "description": "Registration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/EnterpriseRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Enterprise"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/me": {
            "get": {
                "description": "Get enterprise inferred from X-Enterprise-ID header.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enterprise"
                ],
                "summary": "Get my enterprise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Caller enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Enterprise"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/slug/{slug}": {
            "get": {
                "description": "Resolve enterprise details using slug.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enterprise"
                ],
                "summary": "Get enterprise by slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Enterprise"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}": {
            "get": {
                "description": "Get enterprise details by enterprise ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enterprise"
                ],
                "summary": "Get enterprise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Enterprise"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft-delete enterprise and start retention period.",
                "tags": [
                    "enterprise"
                ],
                "summary": "Delete enterprise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update enterprise profile fields.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "enterprise"
                ],
                "summary": "Update enterprise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Enterprise patch payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Enterprise"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/approve": {
            "post": {
                "description": "Approve enterprise onboarding request.",
                "tags": [
                    "enterprise"
                ],
                "summary": "Approve enterprise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/audit-logs": {
            "get": {
                "description": "List paginated audit logs for enterprise actions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enterprise"
                ],
                "summary": "Get audit logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (event, actor_role, created_at)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction (asc, desc)",
                        "name": "sort_dir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedResponse-AuditLog"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/branding": {
            "patch": {
                "description": "Update logo and brand color values.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "enterprise"
                ],
                "summary": "Update branding",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "description": "Branding patch",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateBrandingRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/permanent": {
            "delete": {
                "description": "Permanently delete enterprise data.",
                "tags": [
                    "enterprise"
                ],
                "summary": "Hard delete enterprise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/reactivate": {
            "post": {
                "description": "Reactivate enterprise from suspended state.",
                "tags": [
                    "enterprise"
                ],
                "summary": "Reactivate enterprise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/restore": {
            "post": {
                "description": "Restore a soft-deleted enterprise.",
                "tags": [
                    "enterprise"
                ],
                "summary": "Restore enterprise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/settings": {
            "patch": {
                "description": "Merge/patch enterprise settings object.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "enterprise"
                ],
                "summary": "Update settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "description": "Settings patch object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/status": {
            "get": {
                "description": "Get lifecycle and subscription status view.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enterprise"
                ],
                "summary": "Get enterprise status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EnterpriseStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/summary": {
            "get": {
                "description": "Get compact operational summary for an enterprise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enterprise"
                ],
                "summary": "Get enterprise summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EnterpriseSummary"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/suspend": {
            "post": {
                "description": "Suspend an active enterprise.",
                "tags": [
                    "enterprise"
                ],
                "summary": "Suspend enterprise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/users": {
            "get": {
                "description": "List users belonging to the specified enterprise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "List enterprise users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (email, first_name, last_name, role, created_at)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction (asc, desc)",
                        "name": "sort_dir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedResponse-User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a user account scoped to an enterprise.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create enterprise user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "description": "Create user payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/users/{userId}": {
            "get": {
                "description": "Get a specific enterprise user by user ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get enterprise user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft delete user account. Only admins can delete users.",
                "tags": [
                    "user"
                ],
                "summary": "Delete enterprise user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update profile fields for an enterprise user. Admins can update any user and change roles. Non-admins can only update their own profile and cannot change their role.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update enterprise user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "description": "Update user payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/users/{userId}/activate": {
            "patch": {
                "description": "Reactivate a previously deactivated user account.",
                "tags": [
                    "user"
                ],
                "summary": "Activate enterprise user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/users/{userId}/change-password": {
            "post": {
                "description": "Self-service password change for authenticated users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Change user password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Change password payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/users/{userId}/deactivate": {
            "patch": {
                "description": "Deactivate user account without permanent deletion.",
                "tags": [
                    "user"
                ],
                "summary": "Deactivate enterprise user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/users/{userId}/reset-password": {
            "post": {
                "description": "Reset user password and return temporary password for secure handoff.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Reset user password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ResetPasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enterprises/{enterpriseId}/validate-domain": {
            "post": {
                "description": "Validate TXT/CNAME records for enterprise custom domain.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enterprise"
                ],
                "summary": "Validate custom domain",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Actor user ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DomainValidationResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns a simple JSON indicating the service is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "operationId": "healthCheck",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AuditEvent": {
            "type": "string",
            "enum": [
                "enterprise.created",
                "enterprise.updated",
                "enterprise.approved",
                "enterprise.suspended",
                "enterprise.deleted",
                "enterprise.reactivated",
                "enterprise.restored",
                "enterprise.hard_deleted",
                "enterprise.branding_updated",
                "enterprise.settings_updated",
                "subscription.updated",
                "subscription.canceled",
                "subscription.renewed",
                "subscription.payment_suspended",
                "user.created",
                "user.updated",
                "user.deactivated",
                "user.activated",
                "user.password_reset",
                "user.password_changed",
                "enterprise.domain_validated",
                "user.forgot_password",
                "user.password_reset_via_token",
                "user.deleted"
            ],
            "x-enum-varnames": [
                "EventEnterpriseCreated",
                "EventEnterpriseUpdated",
                "EventEnterpriseApproved",
                "EventEnterpriseSuspended",
                "EventEnterpriseDeleted",
                "EventEnterpriseReactivated",
                "EventEnterpriseRestored",
                "EventEnterpriseHardDeleted",
                "EventBrandingUpdated",
                "EventSettingsUpdated",
                "EventSubscriptionUpdated",
                "EventSubscriptionCanceled",
                "EventSubscriptionRenewed",
                "EventSubscriptionSuspended",
                "EventUserCreated",
                "EventUserUpdated",
                "EventUserDeactivated",
                "EventUserActivated",
                "EventUserPasswordReset",
                "EventUserPasswordChanged",
                "EventDomainValidated",
                "EventUserForgotPassword",
                "EventUserPasswordResetViaToken",
                "EventUserDeleted"
            ]
        },
        "AuditLog": {
            "type": "object",
            "properties": {
                "actor_id": {
                    "type": "string"
                },
                "actor_role": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "enterprise_id": {
                    "type": "string"
                },
                "event": {
                    "$ref": "#/definitions/AuditEvent"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "ChangePasswordRequest": {
            "type": "object",
            "required": [
                "current_password",
                "new_password"
            ],
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "honorific": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/Role"
                }
            }
        },
        "DomainValidationResult": {
            "type": "object",
            "properties": {
                "cname_found": {
                    "type": "boolean"
                },
                "details": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "txt_record_found": {
                    "type": "boolean"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "Enterprise": {
            "type": "object",
            "properties": {
                "addressLine1": {
                    "type": "string"
                },
                "addressLine2": {
                    "type": "string"
                },
                "approvedAt": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "contactEmail": {
                    "type": "string"
                },
                "contactPhone": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "customDomain": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "legalName": {
                    "type": "string"
                },
                "logoUrl": {
                    "type": "string"
                },
                "ownerAccountId": {
                    "type": "string"
                },
                "primaryColor": {
                    "type": "string"
                },
                "retentionUntil": {
                    "type": "string"
                },
                "secondaryColor": {
                    "type": "string"
                },
                "settings": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/EnterpriseStatus"
                },
                "suspendedAt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                }
            }
        },
        "EnterpriseStatus": {
            "type": "string",
            "enum": [
                "PendingApproval",
                "Active",
                "Suspended",
                "Deleted"
            ],
            "x-enum-varnames": [
                "StatusPendingApproval",
                "StatusActive",
                "StatusSuspended",
                "StatusDeleted"
            ]
        },
        "EnterpriseStatusResponse": {
            "type": "object",
            "properties": {
                "approved_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "enterprise_id": {
                    "type": "string"
                },
                "retention_until": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/EnterpriseStatus"
                },
                "subscription": {
                    "$ref": "#/definitions/SubscriptionSnapshot"
                },
                "suspended_at": {
                    "type": "string"
                }
            }
        },
        "EnterpriseSummary": {
            "type": "object",
            "properties": {
                "active_exam_count": {
                    "type": "integer"
                },
                "active_session_count": {
                    "type": "integer"
                },
                "display_name": {
                    "type": "string"
                },
                "enterprise_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/EnterpriseStatus"
                },
                "subscription": {
                    "$ref": "#/definitions/SubscriptionSnapshot"
                },
                "user_count": {
                    "type": "integer"
                }
            }
        },
        "ForgotPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "ResetPasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "token"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "minLength": 8
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "Role": {
            "type": "string",
            "enum": [
                "SystemAdmin",
                "EnterpriseAdmin",
                "EnterpriseAuto",
                "EnterpriseStaff",
                "ExamCandidate"
            ],
            "x-enum-varnames": [
                "RoleSystemAdmin",
                "RoleEnterpriseAdmin",
                "RoleEnterpriseAuto",
                "RoleEnterpriseStaff",
                "RoleExamCandidate"
            ]
        },
        "SubscriptionSnapshot": {
            "type": "object",
            "properties": {
                "cancel_at_period_end": {
                    "type": "boolean"
                },
                "current_period_end": {
                    "type": "string"
                },
                "current_period_start": {
                    "type": "string"
                },
                "plan_id": {
                    "type": "string"
                },
                "plan_name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "UpdateBrandingRequest": {
            "type": "object",
            "properties": {
                "logo_url": {
                    "type": "string"
                },
                "primary_color": {
                    "type": "string"
                },
                "secondary_color": {
                    "type": "string"
                }
            }
        },
        "UpdateUserRequest": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "honorific": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/Role"
                }
            }
        },
        "User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "emailVerified": {
                    "type": "boolean"
                },
                "emailVerifiedAt": {
                    "type": "string"
                },
                "enterpriseId": {
                    "type": "string"
                },
                "failedLoginAttempts": {
                    "type": "integer"
                },
                "firstName": {
                    "type": "string"
                },
                "honorific": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isDeleted": {
                    "type": "boolean"
                },
                "lastLoginAt": {
                    "type": "string"
                },
                "lastLoginIp": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "lastUserAgent": {
                    "type": "string"
                },
                "lockedUntil": {
                    "type": "string"
                },
                "mustChangePassword": {
                    "type": "boolean"
                },
                "passwordChangedAt": {
                    "type": "string"
                },
                "passwordHash": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/Role"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "EnterpriseRegisterRequest": {
            "type": "object",
            "required": [
                "contactEmail",
                "displayName",
                "legalName",
                "ownerEmail",
                "ownerPassword",
                "slug"
            ],
            "properties": {
                "contactEmail": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "legalName": {
                    "type": "string"
                },
                "ownerEmail": {
                    "type": "string"
                },
                "ownerPassword": {
                    "type": "string",
                    "minLength": 8
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "ResetPasswordResponse": {
            "type": "object",
            "properties": {
                "temporary_password": {
                    "type": "string"
                }
            }
        },
        "Metadata": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "has_next": {
                    "type": "boolean"
                },
                "has_previous": {
                    "type": "boolean"
                },
                "page_size": {
                    "type": "integer"
                },
                "total_elements": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "PaginatedResponse-AuditLog": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AuditLog"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/Metadata"
                }
            }
        },
        "PaginatedResponse-Enterprise": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Enterprise"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/Metadata"
                }
            }
        },
        "PaginatedResponse-User": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/User"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/Metadata"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Enterprise profile and lifecycle management endpoints.",
            "name": "enterprise"
        },
        {
            "description": "Enterprise user management endpoints.",
            "name": "user"
        },
        {
            "description": "Operational and health endpoints.",
            "name": "system"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Veritas Enterprise Service API",
	Description:      "Enterprise onboarding, account management, and user administration service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
