// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Veritas Platform Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/subscriptions/{enterpriseId}": {
            "post": {
                "description": "Manually override an enterprise's subscription plan and status (no Stripe call).",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Admin set subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Subscription override",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AdminSetSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns a simple JSON indicating the service is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "operationId": "healthCheck",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/invoices/{invoiceId}": {
            "get": {
                "description": "Fetch a single invoice by invoice ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Get invoice",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invoice ID (UUID)",
                        "name": "invoiceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Invoice"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payments/history": {
            "get": {
                "description": "Returns payment history for the specified enterprise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "List payment history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "X-Enterprise-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Payment"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions/plans": {
            "get": {
                "description": "Returns all available subscription plans.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "List subscription plans",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/SubscriptionPlan"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions/{enterpriseId}": {
            "get": {
                "description": "Returns the current subscription state for an enterprise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Get active subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EnterpriseSubscription"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions/{enterpriseId}/cancel": {
            "post": {
                "description": "Cancels an enterprise subscription immediately or at period end.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Cancel subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancel options",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/CancelSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions/{enterpriseId}/reactivate": {
            "post": {
                "description": "Cancels a pending period-end cancellation, keeping the subscription active.",
                "tags": [
                    "subscription"
                ],
                "summary": "Reactivate subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions/{enterpriseId}/upgrade": {
            "post": {
                "description": "Creates a provider checkout session for upgrading an enterprise subscription plan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Upgrade enterprise subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enterprise ID (UUID)",
                        "name": "enterpriseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Upgrade request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpgradeSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CheckoutURLResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/webhooks/stripe": {
            "post": {
                "description": "Validates and processes Stripe webhook event payload.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "webhook"
                ],
                "summary": "Handle Stripe webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stripe webhook signature",
                        "name": "Stripe-Signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Raw webhook payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "BillingCycle": {
            "type": "string",
            "enum": [
                "monthly",
                "yearly"
            ],
            "x-enum-varnames": [
                "BillingCycleMonthly",
                "BillingCycleYearly"
            ]
        },
        "Currency": {
            "type": "string",
            "enum": [
                "ETB",
                "USD",
                "EUR",
                "GBP"
            ],
            "x-enum-varnames": [
                "CurrencyETB",
                "CurrencyUSD",
                "CurrencyEUR",
                "CurrencyGBP"
            ]
        },
        "EnterpriseSubscription": {
            "type": "object",
            "properties": {
                "cancel_at_period_end": {
                    "type": "boolean"
                },
                "canceled_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "current_period_end": {
                    "type": "string"
                },
                "current_period_start": {
                    "type": "string"
                },
                "ended_at": {
                    "type": "string"
                },
                "enterprise_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "plan_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/SubscriptionStatus"
                },
                "stripe_customer_id": {
                    "type": "string"
                },
                "stripe_subscription_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "Invoice": {
            "type": "object",
            "properties": {
                "amount_due": {
                    "type": "number"
                },
                "amount_paid": {
                    "type": "number"
                },
                "amount_remaining": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "$ref": "#/definitions/Currency"
                },
                "due_date": {
                    "type": "string"
                },
                "enterprise_id": {
                    "type": "string"
                },
                "hosted_invoice_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "invoice_pdf_url": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "paid_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/InvoiceStatus"
                },
                "subscription_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "InvoiceStatus": {
            "type": "string",
            "enum": [
                "Draft",
                "Open",
                "Paid",
                "Void",
                "Uncollectible"
            ],
            "x-enum-varnames": [
                "InvoiceStatusDraft",
                "InvoiceStatusOpen",
                "InvoiceStatusPaid",
                "InvoiceStatusVoid",
                "InvoiceStatusUncollectible"
            ]
        },
        "Payment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "$ref": "#/definitions/Currency"
                },
                "enterprise_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "invoice_id": {
                    "type": "string"
                },
                "payment_method_type": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "provider_error_code": {
                    "type": "string"
                },
                "provider_error_message": {
                    "type": "string"
                },
                "provider_payment_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/PaymentStatus"
                }
            }
        },
        "PaymentStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Succeeded",
                "Failed",
                "Refunded"
            ],
            "x-enum-varnames": [
                "PaymentStatusPending",
                "PaymentStatusSucceeded",
                "PaymentStatusFailed",
                "PaymentStatusRefunded"
            ]
        },
        "SubscriptionPlan": {
            "type": "object",
            "properties": {
                "billing_cycle": {
                    "$ref": "#/definitions/BillingCycle"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "$ref": "#/definitions/Currency"
                },
                "description": {
                    "type": "string"
                },
                "features": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "slug": {
                    "type": "string"
                },
                "stripe_price_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "SubscriptionStatus": {
            "type": "string",
            "enum": [
                "Active",
                "PastDue",
                "Canceled",
                "Expired",
                "Trial"
            ],
            "x-enum-varnames": [
                "SubStatusActive",
                "SubStatusPastDue",
                "SubStatusCanceled",
                "SubStatusExpired",
                "SubStatusTrial"
            ]
        },
        "AdminSetSubscriptionRequest": {
            "type": "object",
            "required": [
                "plan_id",
                "status"
            ],
            "properties": {
                "period_end": {
                    "type": "string"
                },
                "period_start": {
                    "type": "string"
                },
                "plan_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "CancelSubscriptionRequest": {
            "type": "object",
            "properties": {
                "cancel_at_period_end": {
                    "description": "When true, the subscription remains active until the current period ends.\nWhen false (default), it is canceled immediately.",
                    "type": "boolean"
                }
            }
        },
        "CheckoutURLResponse": {
            "type": "object",
            "properties": {
                "checkout_url": {
                    "type": "string"
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "UpgradeSubscriptionRequest": {
            "type": "object",
            "required": [
                "plan_id"
            ],
            "properties": {
                "plan_id": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Payment and billing operations.",
            "name": "payment"
        },
        {
            "description": "Subscription plan and management operations.",
            "name": "subscription"
        },
        {
            "description": "External payment provider webhook endpoints.",
            "name": "webhook"
        },
        {
            "description": "Operational and health endpoints.",
            "name": "system"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Veritas Payment Service API",
	Description:      "Subscription plans, upgrades, cancellations, invoice retrieval, payment history, and Stripe webhook processing.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
